server:
  port: 8080

spring:
  profiles:
    active: jp

initial-data:
  account: 12345678900
  password: 12345678

---
spring:
  profiles: jp
  datasource:
    username: root
    password: sora1212
    url: jdbc:mysql://127.0.0.1:3306/zhixue?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  upload:
    path: D:\\dev


